# Generated by Django 4.2.7 on 2024-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_lessonviewed_delete_lessonview"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonviewed",
            name="last_viewed",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
